// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// CompletedLesson is the predicate function for completedlesson builders.
type CompletedLesson func(*sql.Selector)

// CompletedTask is the predicate function for completedtask builders.
type CompletedTask func(*sql.Selector)

// Lesson is the predicate function for lesson builders.
type Lesson func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)

// UploadedFile is the predicate function for uploadedfile builders.
type UploadedFile func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
