version: "3.8"

services:
  db:
    image: postgres:16.2-alpine3.19
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - ${DB_PORT}:5432
    restart: unless-stopped
    volumes:
      - edu-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
volumes:
  edu-data:
