// Code generated by ent, DO NOT EDIT.

package lesson

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/khiskam/edu-platform/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Lesson {
	return predicate.Lesson(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Lesson {
	return predicate.Lesson(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Lesson {
	return predicate.Lesson(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Lesson {
	return predicate.Lesson(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Lesson {
	return predicate.Lesson(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Lesson {
	return predicate.Lesson(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Lesson {
	return predicate.Lesson(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Lesson {
	return predicate.Lesson(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Lesson {
	return predicate.Lesson(sql.FieldLTE(FieldID, id))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldEQ(FieldTitle, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldEQ(FieldDescription, v))
}

// Layout applies equality check predicate on the "layout" field. It's identical to LayoutEQ.
func Layout(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldEQ(FieldLayout, v))
}

// CategoryID applies equality check predicate on the "category_id" field. It's identical to CategoryIDEQ.
func CategoryID(v uuid.UUID) predicate.Lesson {
	return predicate.Lesson(sql.FieldEQ(FieldCategoryID, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Lesson {
	return predicate.Lesson(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Lesson {
	return predicate.Lesson(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldContainsFold(FieldTitle, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Lesson {
	return predicate.Lesson(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Lesson {
	return predicate.Lesson(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldContainsFold(FieldDescription, v))
}

// LayoutEQ applies the EQ predicate on the "layout" field.
func LayoutEQ(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldEQ(FieldLayout, v))
}

// LayoutNEQ applies the NEQ predicate on the "layout" field.
func LayoutNEQ(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldNEQ(FieldLayout, v))
}

// LayoutIn applies the In predicate on the "layout" field.
func LayoutIn(vs ...string) predicate.Lesson {
	return predicate.Lesson(sql.FieldIn(FieldLayout, vs...))
}

// LayoutNotIn applies the NotIn predicate on the "layout" field.
func LayoutNotIn(vs ...string) predicate.Lesson {
	return predicate.Lesson(sql.FieldNotIn(FieldLayout, vs...))
}

// LayoutGT applies the GT predicate on the "layout" field.
func LayoutGT(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldGT(FieldLayout, v))
}

// LayoutGTE applies the GTE predicate on the "layout" field.
func LayoutGTE(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldGTE(FieldLayout, v))
}

// LayoutLT applies the LT predicate on the "layout" field.
func LayoutLT(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldLT(FieldLayout, v))
}

// LayoutLTE applies the LTE predicate on the "layout" field.
func LayoutLTE(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldLTE(FieldLayout, v))
}

// LayoutContains applies the Contains predicate on the "layout" field.
func LayoutContains(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldContains(FieldLayout, v))
}

// LayoutHasPrefix applies the HasPrefix predicate on the "layout" field.
func LayoutHasPrefix(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldHasPrefix(FieldLayout, v))
}

// LayoutHasSuffix applies the HasSuffix predicate on the "layout" field.
func LayoutHasSuffix(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldHasSuffix(FieldLayout, v))
}

// LayoutEqualFold applies the EqualFold predicate on the "layout" field.
func LayoutEqualFold(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldEqualFold(FieldLayout, v))
}

// LayoutContainsFold applies the ContainsFold predicate on the "layout" field.
func LayoutContainsFold(v string) predicate.Lesson {
	return predicate.Lesson(sql.FieldContainsFold(FieldLayout, v))
}

// CategoryIDEQ applies the EQ predicate on the "category_id" field.
func CategoryIDEQ(v uuid.UUID) predicate.Lesson {
	return predicate.Lesson(sql.FieldEQ(FieldCategoryID, v))
}

// CategoryIDNEQ applies the NEQ predicate on the "category_id" field.
func CategoryIDNEQ(v uuid.UUID) predicate.Lesson {
	return predicate.Lesson(sql.FieldNEQ(FieldCategoryID, v))
}

// CategoryIDIn applies the In predicate on the "category_id" field.
func CategoryIDIn(vs ...uuid.UUID) predicate.Lesson {
	return predicate.Lesson(sql.FieldIn(FieldCategoryID, vs...))
}

// CategoryIDNotIn applies the NotIn predicate on the "category_id" field.
func CategoryIDNotIn(vs ...uuid.UUID) predicate.Lesson {
	return predicate.Lesson(sql.FieldNotIn(FieldCategoryID, vs...))
}

// CategoryIDIsNil applies the IsNil predicate on the "category_id" field.
func CategoryIDIsNil() predicate.Lesson {
	return predicate.Lesson(sql.FieldIsNull(FieldCategoryID))
}

// CategoryIDNotNil applies the NotNil predicate on the "category_id" field.
func CategoryIDNotNil() predicate.Lesson {
	return predicate.Lesson(sql.FieldNotNull(FieldCategoryID))
}

// HasCompletedLessons applies the HasEdge predicate on the "completed_lessons" edge.
func HasCompletedLessons() predicate.Lesson {
	return predicate.Lesson(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CompletedLessonsTable, CompletedLessonsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCompletedLessonsWith applies the HasEdge predicate on the "completed_lessons" edge with a given conditions (other predicates).
func HasCompletedLessonsWith(preds ...predicate.CompletedLesson) predicate.Lesson {
	return predicate.Lesson(func(s *sql.Selector) {
		step := newCompletedLessonsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLesson applies the HasEdge predicate on the "lesson" edge.
func HasLesson() predicate.Lesson {
	return predicate.Lesson(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, LessonTable, LessonColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLessonWith applies the HasEdge predicate on the "lesson" edge with a given conditions (other predicates).
func HasLessonWith(preds ...predicate.Category) predicate.Lesson {
	return predicate.Lesson(func(s *sql.Selector) {
		step := newLessonStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Lesson) predicate.Lesson {
	return predicate.Lesson(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Lesson) predicate.Lesson {
	return predicate.Lesson(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Lesson) predicate.Lesson {
	return predicate.Lesson(sql.NotPredicates(p))
}
