// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/khiskam/edu-platform/backend/ent/completedlesson"
	"github.com/khiskam/edu-platform/backend/ent/lesson"
	"github.com/khiskam/edu-platform/backend/ent/predicate"
	"github.com/khiskam/edu-platform/backend/ent/user"
)

// CompletedLessonQuery is the builder for querying CompletedLesson entities.
type CompletedLessonQuery struct {
	config
	ctx                 *QueryContext
	order               []completedlesson.OrderOption
	inters              []Interceptor
	predicates          []predicate.CompletedLesson
	withAuthor          *UserQuery
	withCompletedLesson *LessonQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CompletedLessonQuery builder.
func (clq *CompletedLessonQuery) Where(ps ...predicate.CompletedLesson) *CompletedLessonQuery {
	clq.predicates = append(clq.predicates, ps...)
	return clq
}

// Limit the number of records to be returned by this query.
func (clq *CompletedLessonQuery) Limit(limit int) *CompletedLessonQuery {
	clq.ctx.Limit = &limit
	return clq
}

// Offset to start from.
func (clq *CompletedLessonQuery) Offset(offset int) *CompletedLessonQuery {
	clq.ctx.Offset = &offset
	return clq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (clq *CompletedLessonQuery) Unique(unique bool) *CompletedLessonQuery {
	clq.ctx.Unique = &unique
	return clq
}

// Order specifies how the records should be ordered.
func (clq *CompletedLessonQuery) Order(o ...completedlesson.OrderOption) *CompletedLessonQuery {
	clq.order = append(clq.order, o...)
	return clq
}

// QueryAuthor chains the current query on the "author" edge.
func (clq *CompletedLessonQuery) QueryAuthor() *UserQuery {
	query := (&UserClient{config: clq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := clq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := clq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(completedlesson.Table, completedlesson.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, completedlesson.AuthorTable, completedlesson.AuthorColumn),
		)
		fromU = sqlgraph.SetNeighbors(clq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCompletedLesson chains the current query on the "completed_lesson" edge.
func (clq *CompletedLessonQuery) QueryCompletedLesson() *LessonQuery {
	query := (&LessonClient{config: clq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := clq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := clq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(completedlesson.Table, completedlesson.FieldID, selector),
			sqlgraph.To(lesson.Table, lesson.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, completedlesson.CompletedLessonTable, completedlesson.CompletedLessonColumn),
		)
		fromU = sqlgraph.SetNeighbors(clq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CompletedLesson entity from the query.
// Returns a *NotFoundError when no CompletedLesson was found.
func (clq *CompletedLessonQuery) First(ctx context.Context) (*CompletedLesson, error) {
	nodes, err := clq.Limit(1).All(setContextOp(ctx, clq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{completedlesson.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (clq *CompletedLessonQuery) FirstX(ctx context.Context) *CompletedLesson {
	node, err := clq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CompletedLesson ID from the query.
// Returns a *NotFoundError when no CompletedLesson ID was found.
func (clq *CompletedLessonQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = clq.Limit(1).IDs(setContextOp(ctx, clq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{completedlesson.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (clq *CompletedLessonQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := clq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CompletedLesson entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CompletedLesson entity is found.
// Returns a *NotFoundError when no CompletedLesson entities are found.
func (clq *CompletedLessonQuery) Only(ctx context.Context) (*CompletedLesson, error) {
	nodes, err := clq.Limit(2).All(setContextOp(ctx, clq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{completedlesson.Label}
	default:
		return nil, &NotSingularError{completedlesson.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (clq *CompletedLessonQuery) OnlyX(ctx context.Context) *CompletedLesson {
	node, err := clq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CompletedLesson ID in the query.
// Returns a *NotSingularError when more than one CompletedLesson ID is found.
// Returns a *NotFoundError when no entities are found.
func (clq *CompletedLessonQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = clq.Limit(2).IDs(setContextOp(ctx, clq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{completedlesson.Label}
	default:
		err = &NotSingularError{completedlesson.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (clq *CompletedLessonQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := clq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CompletedLessons.
func (clq *CompletedLessonQuery) All(ctx context.Context) ([]*CompletedLesson, error) {
	ctx = setContextOp(ctx, clq.ctx, "All")
	if err := clq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CompletedLesson, *CompletedLessonQuery]()
	return withInterceptors[[]*CompletedLesson](ctx, clq, qr, clq.inters)
}

// AllX is like All, but panics if an error occurs.
func (clq *CompletedLessonQuery) AllX(ctx context.Context) []*CompletedLesson {
	nodes, err := clq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CompletedLesson IDs.
func (clq *CompletedLessonQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if clq.ctx.Unique == nil && clq.path != nil {
		clq.Unique(true)
	}
	ctx = setContextOp(ctx, clq.ctx, "IDs")
	if err = clq.Select(completedlesson.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (clq *CompletedLessonQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := clq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (clq *CompletedLessonQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, clq.ctx, "Count")
	if err := clq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, clq, querierCount[*CompletedLessonQuery](), clq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (clq *CompletedLessonQuery) CountX(ctx context.Context) int {
	count, err := clq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (clq *CompletedLessonQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, clq.ctx, "Exist")
	switch _, err := clq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (clq *CompletedLessonQuery) ExistX(ctx context.Context) bool {
	exist, err := clq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CompletedLessonQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (clq *CompletedLessonQuery) Clone() *CompletedLessonQuery {
	if clq == nil {
		return nil
	}
	return &CompletedLessonQuery{
		config:              clq.config,
		ctx:                 clq.ctx.Clone(),
		order:               append([]completedlesson.OrderOption{}, clq.order...),
		inters:              append([]Interceptor{}, clq.inters...),
		predicates:          append([]predicate.CompletedLesson{}, clq.predicates...),
		withAuthor:          clq.withAuthor.Clone(),
		withCompletedLesson: clq.withCompletedLesson.Clone(),
		// clone intermediate query.
		sql:  clq.sql.Clone(),
		path: clq.path,
	}
}

// WithAuthor tells the query-builder to eager-load the nodes that are connected to
// the "author" edge. The optional arguments are used to configure the query builder of the edge.
func (clq *CompletedLessonQuery) WithAuthor(opts ...func(*UserQuery)) *CompletedLessonQuery {
	query := (&UserClient{config: clq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	clq.withAuthor = query
	return clq
}

// WithCompletedLesson tells the query-builder to eager-load the nodes that are connected to
// the "completed_lesson" edge. The optional arguments are used to configure the query builder of the edge.
func (clq *CompletedLessonQuery) WithCompletedLesson(opts ...func(*LessonQuery)) *CompletedLessonQuery {
	query := (&LessonClient{config: clq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	clq.withCompletedLesson = query
	return clq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID uuid.UUID `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CompletedLesson.Query().
//		GroupBy(completedlesson.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (clq *CompletedLessonQuery) GroupBy(field string, fields ...string) *CompletedLessonGroupBy {
	clq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CompletedLessonGroupBy{build: clq}
	grbuild.flds = &clq.ctx.Fields
	grbuild.label = completedlesson.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID uuid.UUID `json:"user_id,omitempty"`
//	}
//
//	client.CompletedLesson.Query().
//		Select(completedlesson.FieldUserID).
//		Scan(ctx, &v)
func (clq *CompletedLessonQuery) Select(fields ...string) *CompletedLessonSelect {
	clq.ctx.Fields = append(clq.ctx.Fields, fields...)
	sbuild := &CompletedLessonSelect{CompletedLessonQuery: clq}
	sbuild.label = completedlesson.Label
	sbuild.flds, sbuild.scan = &clq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CompletedLessonSelect configured with the given aggregations.
func (clq *CompletedLessonQuery) Aggregate(fns ...AggregateFunc) *CompletedLessonSelect {
	return clq.Select().Aggregate(fns...)
}

func (clq *CompletedLessonQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range clq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, clq); err != nil {
				return err
			}
		}
	}
	for _, f := range clq.ctx.Fields {
		if !completedlesson.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if clq.path != nil {
		prev, err := clq.path(ctx)
		if err != nil {
			return err
		}
		clq.sql = prev
	}
	return nil
}

func (clq *CompletedLessonQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CompletedLesson, error) {
	var (
		nodes       = []*CompletedLesson{}
		_spec       = clq.querySpec()
		loadedTypes = [2]bool{
			clq.withAuthor != nil,
			clq.withCompletedLesson != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CompletedLesson).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CompletedLesson{config: clq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, clq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := clq.withAuthor; query != nil {
		if err := clq.loadAuthor(ctx, query, nodes, nil,
			func(n *CompletedLesson, e *User) { n.Edges.Author = e }); err != nil {
			return nil, err
		}
	}
	if query := clq.withCompletedLesson; query != nil {
		if err := clq.loadCompletedLesson(ctx, query, nodes, nil,
			func(n *CompletedLesson, e *Lesson) { n.Edges.CompletedLesson = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (clq *CompletedLessonQuery) loadAuthor(ctx context.Context, query *UserQuery, nodes []*CompletedLesson, init func(*CompletedLesson), assign func(*CompletedLesson, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*CompletedLesson)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (clq *CompletedLessonQuery) loadCompletedLesson(ctx context.Context, query *LessonQuery, nodes []*CompletedLesson, init func(*CompletedLesson), assign func(*CompletedLesson, *Lesson)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*CompletedLesson)
	for i := range nodes {
		fk := nodes[i].LessonID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(lesson.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "lesson_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (clq *CompletedLessonQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := clq.querySpec()
	_spec.Node.Columns = clq.ctx.Fields
	if len(clq.ctx.Fields) > 0 {
		_spec.Unique = clq.ctx.Unique != nil && *clq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, clq.driver, _spec)
}

func (clq *CompletedLessonQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(completedlesson.Table, completedlesson.Columns, sqlgraph.NewFieldSpec(completedlesson.FieldID, field.TypeUUID))
	_spec.From = clq.sql
	if unique := clq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if clq.path != nil {
		_spec.Unique = true
	}
	if fields := clq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, completedlesson.FieldID)
		for i := range fields {
			if fields[i] != completedlesson.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if clq.withAuthor != nil {
			_spec.Node.AddColumnOnce(completedlesson.FieldUserID)
		}
		if clq.withCompletedLesson != nil {
			_spec.Node.AddColumnOnce(completedlesson.FieldLessonID)
		}
	}
	if ps := clq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := clq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := clq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := clq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (clq *CompletedLessonQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(clq.driver.Dialect())
	t1 := builder.Table(completedlesson.Table)
	columns := clq.ctx.Fields
	if len(columns) == 0 {
		columns = completedlesson.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if clq.sql != nil {
		selector = clq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if clq.ctx.Unique != nil && *clq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range clq.predicates {
		p(selector)
	}
	for _, p := range clq.order {
		p(selector)
	}
	if offset := clq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := clq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CompletedLessonGroupBy is the group-by builder for CompletedLesson entities.
type CompletedLessonGroupBy struct {
	selector
	build *CompletedLessonQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (clgb *CompletedLessonGroupBy) Aggregate(fns ...AggregateFunc) *CompletedLessonGroupBy {
	clgb.fns = append(clgb.fns, fns...)
	return clgb
}

// Scan applies the selector query and scans the result into the given value.
func (clgb *CompletedLessonGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, clgb.build.ctx, "GroupBy")
	if err := clgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CompletedLessonQuery, *CompletedLessonGroupBy](ctx, clgb.build, clgb, clgb.build.inters, v)
}

func (clgb *CompletedLessonGroupBy) sqlScan(ctx context.Context, root *CompletedLessonQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(clgb.fns))
	for _, fn := range clgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*clgb.flds)+len(clgb.fns))
		for _, f := range *clgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*clgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := clgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CompletedLessonSelect is the builder for selecting fields of CompletedLesson entities.
type CompletedLessonSelect struct {
	*CompletedLessonQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cls *CompletedLessonSelect) Aggregate(fns ...AggregateFunc) *CompletedLessonSelect {
	cls.fns = append(cls.fns, fns...)
	return cls
}

// Scan applies the selector query and scans the result into the given value.
func (cls *CompletedLessonSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cls.ctx, "Select")
	if err := cls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CompletedLessonQuery, *CompletedLessonSelect](ctx, cls.CompletedLessonQuery, cls, cls.inters, v)
}

func (cls *CompletedLessonSelect) sqlScan(ctx context.Context, root *CompletedLessonQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cls.fns))
	for _, fn := range cls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
