// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/khiskam/edu-platform/backend/ent/completedlesson"
	"github.com/khiskam/edu-platform/backend/ent/predicate"
)

// CompletedLessonDelete is the builder for deleting a CompletedLesson entity.
type CompletedLessonDelete struct {
	config
	hooks    []Hook
	mutation *CompletedLessonMutation
}

// Where appends a list predicates to the CompletedLessonDelete builder.
func (cld *CompletedLessonDelete) Where(ps ...predicate.CompletedLesson) *CompletedLessonDelete {
	cld.mutation.Where(ps...)
	return cld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cld *CompletedLessonDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, cld.sqlExec, cld.mutation, cld.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (cld *CompletedLessonDelete) ExecX(ctx context.Context) int {
	n, err := cld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cld *CompletedLessonDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(completedlesson.Table, sqlgraph.NewFieldSpec(completedlesson.FieldID, field.TypeUUID))
	if ps := cld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, cld.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	cld.mutation.done = true
	return affected, err
}

// CompletedLessonDeleteOne is the builder for deleting a single CompletedLesson entity.
type CompletedLessonDeleteOne struct {
	cld *CompletedLessonDelete
}

// Where appends a list predicates to the CompletedLessonDelete builder.
func (cldo *CompletedLessonDeleteOne) Where(ps ...predicate.CompletedLesson) *CompletedLessonDeleteOne {
	cldo.cld.mutation.Where(ps...)
	return cldo
}

// Exec executes the deletion query.
func (cldo *CompletedLessonDeleteOne) Exec(ctx context.Context) error {
	n, err := cldo.cld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{completedlesson.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cldo *CompletedLessonDeleteOne) ExecX(ctx context.Context) {
	if err := cldo.Exec(ctx); err != nil {
		panic(err)
	}
}
