// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/khiskam/edu-platform/backend/ent/completedtask"
	"github.com/khiskam/edu-platform/backend/ent/predicate"
	"github.com/khiskam/edu-platform/backend/ent/task"
	"github.com/khiskam/edu-platform/backend/ent/user"
)

// CompletedTaskQuery is the builder for querying CompletedTask entities.
type CompletedTaskQuery struct {
	config
	ctx               *QueryContext
	order             []completedtask.OrderOption
	inters            []Interceptor
	predicates        []predicate.CompletedTask
	withAuthor        *UserQuery
	withCompletedTask *TaskQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CompletedTaskQuery builder.
func (ctq *CompletedTaskQuery) Where(ps ...predicate.CompletedTask) *CompletedTaskQuery {
	ctq.predicates = append(ctq.predicates, ps...)
	return ctq
}

// Limit the number of records to be returned by this query.
func (ctq *CompletedTaskQuery) Limit(limit int) *CompletedTaskQuery {
	ctq.ctx.Limit = &limit
	return ctq
}

// Offset to start from.
func (ctq *CompletedTaskQuery) Offset(offset int) *CompletedTaskQuery {
	ctq.ctx.Offset = &offset
	return ctq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ctq *CompletedTaskQuery) Unique(unique bool) *CompletedTaskQuery {
	ctq.ctx.Unique = &unique
	return ctq
}

// Order specifies how the records should be ordered.
func (ctq *CompletedTaskQuery) Order(o ...completedtask.OrderOption) *CompletedTaskQuery {
	ctq.order = append(ctq.order, o...)
	return ctq
}

// QueryAuthor chains the current query on the "author" edge.
func (ctq *CompletedTaskQuery) QueryAuthor() *UserQuery {
	query := (&UserClient{config: ctq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ctq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ctq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(completedtask.Table, completedtask.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, completedtask.AuthorTable, completedtask.AuthorColumn),
		)
		fromU = sqlgraph.SetNeighbors(ctq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCompletedTask chains the current query on the "completed_task" edge.
func (ctq *CompletedTaskQuery) QueryCompletedTask() *TaskQuery {
	query := (&TaskClient{config: ctq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ctq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ctq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(completedtask.Table, completedtask.FieldID, selector),
			sqlgraph.To(task.Table, task.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, completedtask.CompletedTaskTable, completedtask.CompletedTaskColumn),
		)
		fromU = sqlgraph.SetNeighbors(ctq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CompletedTask entity from the query.
// Returns a *NotFoundError when no CompletedTask was found.
func (ctq *CompletedTaskQuery) First(ctx context.Context) (*CompletedTask, error) {
	nodes, err := ctq.Limit(1).All(setContextOp(ctx, ctq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{completedtask.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ctq *CompletedTaskQuery) FirstX(ctx context.Context) *CompletedTask {
	node, err := ctq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CompletedTask ID from the query.
// Returns a *NotFoundError when no CompletedTask ID was found.
func (ctq *CompletedTaskQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = ctq.Limit(1).IDs(setContextOp(ctx, ctq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{completedtask.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ctq *CompletedTaskQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := ctq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CompletedTask entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CompletedTask entity is found.
// Returns a *NotFoundError when no CompletedTask entities are found.
func (ctq *CompletedTaskQuery) Only(ctx context.Context) (*CompletedTask, error) {
	nodes, err := ctq.Limit(2).All(setContextOp(ctx, ctq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{completedtask.Label}
	default:
		return nil, &NotSingularError{completedtask.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ctq *CompletedTaskQuery) OnlyX(ctx context.Context) *CompletedTask {
	node, err := ctq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CompletedTask ID in the query.
// Returns a *NotSingularError when more than one CompletedTask ID is found.
// Returns a *NotFoundError when no entities are found.
func (ctq *CompletedTaskQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = ctq.Limit(2).IDs(setContextOp(ctx, ctq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{completedtask.Label}
	default:
		err = &NotSingularError{completedtask.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ctq *CompletedTaskQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := ctq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CompletedTasks.
func (ctq *CompletedTaskQuery) All(ctx context.Context) ([]*CompletedTask, error) {
	ctx = setContextOp(ctx, ctq.ctx, "All")
	if err := ctq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CompletedTask, *CompletedTaskQuery]()
	return withInterceptors[[]*CompletedTask](ctx, ctq, qr, ctq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ctq *CompletedTaskQuery) AllX(ctx context.Context) []*CompletedTask {
	nodes, err := ctq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CompletedTask IDs.
func (ctq *CompletedTaskQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if ctq.ctx.Unique == nil && ctq.path != nil {
		ctq.Unique(true)
	}
	ctx = setContextOp(ctx, ctq.ctx, "IDs")
	if err = ctq.Select(completedtask.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ctq *CompletedTaskQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := ctq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ctq *CompletedTaskQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ctq.ctx, "Count")
	if err := ctq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ctq, querierCount[*CompletedTaskQuery](), ctq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ctq *CompletedTaskQuery) CountX(ctx context.Context) int {
	count, err := ctq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ctq *CompletedTaskQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ctq.ctx, "Exist")
	switch _, err := ctq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ctq *CompletedTaskQuery) ExistX(ctx context.Context) bool {
	exist, err := ctq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CompletedTaskQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ctq *CompletedTaskQuery) Clone() *CompletedTaskQuery {
	if ctq == nil {
		return nil
	}
	return &CompletedTaskQuery{
		config:            ctq.config,
		ctx:               ctq.ctx.Clone(),
		order:             append([]completedtask.OrderOption{}, ctq.order...),
		inters:            append([]Interceptor{}, ctq.inters...),
		predicates:        append([]predicate.CompletedTask{}, ctq.predicates...),
		withAuthor:        ctq.withAuthor.Clone(),
		withCompletedTask: ctq.withCompletedTask.Clone(),
		// clone intermediate query.
		sql:  ctq.sql.Clone(),
		path: ctq.path,
	}
}

// WithAuthor tells the query-builder to eager-load the nodes that are connected to
// the "author" edge. The optional arguments are used to configure the query builder of the edge.
func (ctq *CompletedTaskQuery) WithAuthor(opts ...func(*UserQuery)) *CompletedTaskQuery {
	query := (&UserClient{config: ctq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ctq.withAuthor = query
	return ctq
}

// WithCompletedTask tells the query-builder to eager-load the nodes that are connected to
// the "completed_task" edge. The optional arguments are used to configure the query builder of the edge.
func (ctq *CompletedTaskQuery) WithCompletedTask(opts ...func(*TaskQuery)) *CompletedTaskQuery {
	query := (&TaskClient{config: ctq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ctq.withCompletedTask = query
	return ctq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Answer string `json:"answer,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CompletedTask.Query().
//		GroupBy(completedtask.FieldAnswer).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ctq *CompletedTaskQuery) GroupBy(field string, fields ...string) *CompletedTaskGroupBy {
	ctq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CompletedTaskGroupBy{build: ctq}
	grbuild.flds = &ctq.ctx.Fields
	grbuild.label = completedtask.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Answer string `json:"answer,omitempty"`
//	}
//
//	client.CompletedTask.Query().
//		Select(completedtask.FieldAnswer).
//		Scan(ctx, &v)
func (ctq *CompletedTaskQuery) Select(fields ...string) *CompletedTaskSelect {
	ctq.ctx.Fields = append(ctq.ctx.Fields, fields...)
	sbuild := &CompletedTaskSelect{CompletedTaskQuery: ctq}
	sbuild.label = completedtask.Label
	sbuild.flds, sbuild.scan = &ctq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CompletedTaskSelect configured with the given aggregations.
func (ctq *CompletedTaskQuery) Aggregate(fns ...AggregateFunc) *CompletedTaskSelect {
	return ctq.Select().Aggregate(fns...)
}

func (ctq *CompletedTaskQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ctq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ctq); err != nil {
				return err
			}
		}
	}
	for _, f := range ctq.ctx.Fields {
		if !completedtask.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ctq.path != nil {
		prev, err := ctq.path(ctx)
		if err != nil {
			return err
		}
		ctq.sql = prev
	}
	return nil
}

func (ctq *CompletedTaskQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CompletedTask, error) {
	var (
		nodes       = []*CompletedTask{}
		_spec       = ctq.querySpec()
		loadedTypes = [2]bool{
			ctq.withAuthor != nil,
			ctq.withCompletedTask != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CompletedTask).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CompletedTask{config: ctq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ctq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ctq.withAuthor; query != nil {
		if err := ctq.loadAuthor(ctx, query, nodes, nil,
			func(n *CompletedTask, e *User) { n.Edges.Author = e }); err != nil {
			return nil, err
		}
	}
	if query := ctq.withCompletedTask; query != nil {
		if err := ctq.loadCompletedTask(ctx, query, nodes, nil,
			func(n *CompletedTask, e *Task) { n.Edges.CompletedTask = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ctq *CompletedTaskQuery) loadAuthor(ctx context.Context, query *UserQuery, nodes []*CompletedTask, init func(*CompletedTask), assign func(*CompletedTask, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*CompletedTask)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (ctq *CompletedTaskQuery) loadCompletedTask(ctx context.Context, query *TaskQuery, nodes []*CompletedTask, init func(*CompletedTask), assign func(*CompletedTask, *Task)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*CompletedTask)
	for i := range nodes {
		fk := nodes[i].TaskID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(task.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "task_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (ctq *CompletedTaskQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ctq.querySpec()
	_spec.Node.Columns = ctq.ctx.Fields
	if len(ctq.ctx.Fields) > 0 {
		_spec.Unique = ctq.ctx.Unique != nil && *ctq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ctq.driver, _spec)
}

func (ctq *CompletedTaskQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(completedtask.Table, completedtask.Columns, sqlgraph.NewFieldSpec(completedtask.FieldID, field.TypeUUID))
	_spec.From = ctq.sql
	if unique := ctq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ctq.path != nil {
		_spec.Unique = true
	}
	if fields := ctq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, completedtask.FieldID)
		for i := range fields {
			if fields[i] != completedtask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if ctq.withAuthor != nil {
			_spec.Node.AddColumnOnce(completedtask.FieldUserID)
		}
		if ctq.withCompletedTask != nil {
			_spec.Node.AddColumnOnce(completedtask.FieldTaskID)
		}
	}
	if ps := ctq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ctq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ctq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ctq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ctq *CompletedTaskQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ctq.driver.Dialect())
	t1 := builder.Table(completedtask.Table)
	columns := ctq.ctx.Fields
	if len(columns) == 0 {
		columns = completedtask.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ctq.sql != nil {
		selector = ctq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ctq.ctx.Unique != nil && *ctq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ctq.predicates {
		p(selector)
	}
	for _, p := range ctq.order {
		p(selector)
	}
	if offset := ctq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ctq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CompletedTaskGroupBy is the group-by builder for CompletedTask entities.
type CompletedTaskGroupBy struct {
	selector
	build *CompletedTaskQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ctgb *CompletedTaskGroupBy) Aggregate(fns ...AggregateFunc) *CompletedTaskGroupBy {
	ctgb.fns = append(ctgb.fns, fns...)
	return ctgb
}

// Scan applies the selector query and scans the result into the given value.
func (ctgb *CompletedTaskGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ctgb.build.ctx, "GroupBy")
	if err := ctgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CompletedTaskQuery, *CompletedTaskGroupBy](ctx, ctgb.build, ctgb, ctgb.build.inters, v)
}

func (ctgb *CompletedTaskGroupBy) sqlScan(ctx context.Context, root *CompletedTaskQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ctgb.fns))
	for _, fn := range ctgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ctgb.flds)+len(ctgb.fns))
		for _, f := range *ctgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ctgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ctgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CompletedTaskSelect is the builder for selecting fields of CompletedTask entities.
type CompletedTaskSelect struct {
	*CompletedTaskQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cts *CompletedTaskSelect) Aggregate(fns ...AggregateFunc) *CompletedTaskSelect {
	cts.fns = append(cts.fns, fns...)
	return cts
}

// Scan applies the selector query and scans the result into the given value.
func (cts *CompletedTaskSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cts.ctx, "Select")
	if err := cts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CompletedTaskQuery, *CompletedTaskSelect](ctx, cts.CompletedTaskQuery, cts, cts.inters, v)
}

func (cts *CompletedTaskSelect) sqlScan(ctx context.Context, root *CompletedTaskQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cts.fns))
	for _, fn := range cts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
