// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/khiskam/edu-platform/backend/ent/category"
	"github.com/khiskam/edu-platform/backend/ent/completedlesson"
	"github.com/khiskam/edu-platform/backend/ent/lesson"
)

// LessonCreate is the builder for creating a Lesson entity.
type LessonCreate struct {
	config
	mutation *LessonMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (lc *LessonCreate) SetTitle(s string) *LessonCreate {
	lc.mutation.SetTitle(s)
	return lc
}

// SetDescription sets the "description" field.
func (lc *LessonCreate) SetDescription(s string) *LessonCreate {
	lc.mutation.SetDescription(s)
	return lc
}

// SetLayout sets the "layout" field.
func (lc *LessonCreate) SetLayout(s string) *LessonCreate {
	lc.mutation.SetLayout(s)
	return lc
}

// SetCategoryID sets the "category_id" field.
func (lc *LessonCreate) SetCategoryID(u uuid.UUID) *LessonCreate {
	lc.mutation.SetCategoryID(u)
	return lc
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (lc *LessonCreate) SetNillableCategoryID(u *uuid.UUID) *LessonCreate {
	if u != nil {
		lc.SetCategoryID(*u)
	}
	return lc
}

// SetID sets the "id" field.
func (lc *LessonCreate) SetID(u uuid.UUID) *LessonCreate {
	lc.mutation.SetID(u)
	return lc
}

// AddCompletedLessonIDs adds the "completed_lessons" edge to the CompletedLesson entity by IDs.
func (lc *LessonCreate) AddCompletedLessonIDs(ids ...uuid.UUID) *LessonCreate {
	lc.mutation.AddCompletedLessonIDs(ids...)
	return lc
}

// AddCompletedLessons adds the "completed_lessons" edges to the CompletedLesson entity.
func (lc *LessonCreate) AddCompletedLessons(c ...*CompletedLesson) *LessonCreate {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return lc.AddCompletedLessonIDs(ids...)
}

// SetLessonID sets the "lesson" edge to the Category entity by ID.
func (lc *LessonCreate) SetLessonID(id uuid.UUID) *LessonCreate {
	lc.mutation.SetLessonID(id)
	return lc
}

// SetNillableLessonID sets the "lesson" edge to the Category entity by ID if the given value is not nil.
func (lc *LessonCreate) SetNillableLessonID(id *uuid.UUID) *LessonCreate {
	if id != nil {
		lc = lc.SetLessonID(*id)
	}
	return lc
}

// SetLesson sets the "lesson" edge to the Category entity.
func (lc *LessonCreate) SetLesson(c *Category) *LessonCreate {
	return lc.SetLessonID(c.ID)
}

// Mutation returns the LessonMutation object of the builder.
func (lc *LessonCreate) Mutation() *LessonMutation {
	return lc.mutation
}

// Save creates the Lesson in the database.
func (lc *LessonCreate) Save(ctx context.Context) (*Lesson, error) {
	return withHooks(ctx, lc.sqlSave, lc.mutation, lc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (lc *LessonCreate) SaveX(ctx context.Context) *Lesson {
	v, err := lc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lc *LessonCreate) Exec(ctx context.Context) error {
	_, err := lc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lc *LessonCreate) ExecX(ctx context.Context) {
	if err := lc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (lc *LessonCreate) check() error {
	if _, ok := lc.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Lesson.title"`)}
	}
	if _, ok := lc.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Lesson.description"`)}
	}
	if _, ok := lc.mutation.Layout(); !ok {
		return &ValidationError{Name: "layout", err: errors.New(`ent: missing required field "Lesson.layout"`)}
	}
	return nil
}

func (lc *LessonCreate) sqlSave(ctx context.Context) (*Lesson, error) {
	if err := lc.check(); err != nil {
		return nil, err
	}
	_node, _spec := lc.createSpec()
	if err := sqlgraph.CreateNode(ctx, lc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	lc.mutation.id = &_node.ID
	lc.mutation.done = true
	return _node, nil
}

func (lc *LessonCreate) createSpec() (*Lesson, *sqlgraph.CreateSpec) {
	var (
		_node = &Lesson{config: lc.config}
		_spec = sqlgraph.NewCreateSpec(lesson.Table, sqlgraph.NewFieldSpec(lesson.FieldID, field.TypeUUID))
	)
	if id, ok := lc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := lc.mutation.Title(); ok {
		_spec.SetField(lesson.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := lc.mutation.Description(); ok {
		_spec.SetField(lesson.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := lc.mutation.Layout(); ok {
		_spec.SetField(lesson.FieldLayout, field.TypeString, value)
		_node.Layout = value
	}
	if nodes := lc.mutation.CompletedLessonsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lesson.CompletedLessonsTable,
			Columns: []string{lesson.CompletedLessonsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(completedlesson.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := lc.mutation.LessonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lesson.LessonTable,
			Columns: []string{lesson.LessonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CategoryID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LessonCreateBulk is the builder for creating many Lesson entities in bulk.
type LessonCreateBulk struct {
	config
	err      error
	builders []*LessonCreate
}

// Save creates the Lesson entities in the database.
func (lcb *LessonCreateBulk) Save(ctx context.Context) ([]*Lesson, error) {
	if lcb.err != nil {
		return nil, lcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(lcb.builders))
	nodes := make([]*Lesson, len(lcb.builders))
	mutators := make([]Mutator, len(lcb.builders))
	for i := range lcb.builders {
		func(i int, root context.Context) {
			builder := lcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LessonMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, lcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, lcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, lcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (lcb *LessonCreateBulk) SaveX(ctx context.Context) []*Lesson {
	v, err := lcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lcb *LessonCreateBulk) Exec(ctx context.Context) error {
	_, err := lcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lcb *LessonCreateBulk) ExecX(ctx context.Context) {
	if err := lcb.Exec(ctx); err != nil {
		panic(err)
	}
}
